In [1]:
import pandas as pd
import json
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')

voting_data = pd.read_csv("https://www.electoralcommission.org.uk/__data/assets/file/0014/212135/EU-referendum-result-data.csv")
county_vote_df = voting_data[['Region','Area', 'Electorate', 'Pct_Turnout', 'Valid_Votes', 'Remain', 'Leave']]
county_vote_df.name = 'county_vote_df'
region_vote_df = voting_data[['Region', 'Electorate', 'Pct_Turnout', 'Valid_Votes', 'Remain', 'Leave']].groupby('Region').agg(np.sum)
region_vote_df.name = 'region_vote_df'

dataframes = [county_vote_df, region_vote_df]
for dataframe in dataframes:
    dataframe.loc[:,'Pct_Remain'] = dataframe['Remain']/dataframe['Valid_Votes']
    dataframe.loc[:,'Pct_Leave'] = dataframe['Leave']/dataframe['Valid_Votes']
     
    output_file = os.path.join('..', 'Resources', dataframe.name +'.csv')
    #  Open the output file
    with open(output_file, 'w') as datafile:
        dataframe.to_csv(output_file)
        
strong_leave_df = county_vote_df[county_vote_df["Pct_Leave"] > .65]
strong_leave_df.name = 'strong_leave_df'
output_file = os.path.join('..', 'Resources', strong_leave_df.name +'.csv')
with open(output_file, 'w') as datafile:
        strong_leave_df.to_csv(output_file)
strong_remain_df = county_vote_df[county_vote_df["Pct_Remain"] > .65]
strong_remain_df.name = 'strong_remain_df'
output_file = os.path.join('..', 'Resources', strong_remain_df.name +'.csv')
with open(output_file, 'w') as datafile:
        strong_remain_df.to_csv(output_file)

In [2]:
strong_leave_df

,Region,Area,Electorate,Pct_Turnout,Valid_Votes,Remain,Leave,Pct_Remain,Pct_Leave
3,East,Thurrock,109897,72.75,79916,22151,57765,0.277179,0.722821
8,East,Fenland,71447,73.69,52626,15055,37571,0.286075,0.713925
11,East,Basildon,132771,73.86,97999,30748,67251,0.313758,0.686242
14,East,Castle Point,68860,75.38,51845,14154,37691,0.273006,0.726994
18,East,Harlow,59124,73.56,43469,13867,29602,0.319009,0.680991
20,East,Rochford,66589,78.81,52447,17510,34937,0.333861,0.666139
21,East,Tendring,111167,74.40,82657,25210,57447,0.304995,0.695005
23,East,Broxbourne,68997,73.78,50872,17166,33706,0.337435,0.662565
31,East,Great Yarmouth,72634,69.06,50128,14284,35844,0.284951,0.715049
32,East,King's Lynn and West Norfolk,113884,74.75,85080,28587,56493,0.336001,0.663999
52,East Midlands,Bolsover,58063,72.33,41972,12242,29730,0.291671,0.708329
66,East Midlands,Boston,39363,77.27,30404,7430,22974,0.244376,0.755624
67,East Midlands,East Lindsey,107009,74.93,80128,23515,56613,0.293468,0.706532
70,East Midlands,South Holland,65701,75.37,49497,13074,36423,0.264137,0.735863
80,East Midlands,Ashfield,91916,72.83,66899,20179,46720,0.301634,0.698366
81,East Midlands,Bassetlaw,85547,74.82,63967,20575,43392,0.321650,0.678350
84,East Midlands,Mansfield,77624,72.62,56344,16417,39927,0.291371,0.708629
102,London,Havering,183082,76.02,139086,42201,96885,0.303417,0.696583
120,North East,Hartlepool,70341,65.59,46100,14029,32071,0.304317,0.695683
121,North East,Middlesbrough,94612,64.89,61358,21181,40177,0.345204,0.654796
122,North East,Redcar and Cleveland,103529,70.26,72714,24586,48128,0.338119,0.661881
135,North West,Blackpool,102354,65.42,66927,21781,45146,0.325444,0.674556
144,North West,Burnley,64461,67.25,43316,14462,28854,0.333872,0.666128
147,North West,Hyndburn,62042,64.74,40137,13569,26568,0.338067,0.661933
240,South East,Gravesham,72808,74.93,54519,18876,35643,0.346228,0.653772
333,West Midlands,Stoke-on-Trent,179010,65.74,117590,36027,81563,0.306378,0.693622
335,West Midlands,Cannock Chase,75010,71.47,53578,16684,36894,0.311396,0.688604
342,West Midlands,Tamworth,56825,74.18,42129,13705,28424,0.325310,0.674690
343,West Midlands,North Warwickshire,49790,76.27,37954,12569,25385,0.331164,0.668836
344,West Midlands,Nuneaton and Bedworth,93978,74.35,69831,23736,46095,0.339906,0.660094
356,West Midlands,Dudley,244516,71.71,175226,56780,118446,0.324039,0.675961
357,West Midlands,Sandwell,221429,66.58,147254,49004,98250,0.332786,0.667214
359,West Midlands,Walsall,194729,69.68,135579,43572,92007,0.321377,0.678623
361,Yorkshire and The Humber,"Kingston upon Hull, City of",180230,62.94,113355,36709,76646,0.323841,0.676159
363,Yorkshire and The Humber,North East Lincolnshire,116302,67.94,78982,23797,55185,0.301296,0.698704
364,Yorkshire and The Humber,North Lincolnshire,123611,71.92,88862,29947,58915,0.337006,0.662994
373,Yorkshire and The Humber,Barnsley,175809,69.95,122909,38951,83958,0.316909,0.683091
374,Yorkshire and The Humber,Doncaster,217432,69.56,151182,46922,104260,0.310368,0.689632
375,Yorkshire and The Humber,Rotherham,197623,69.56,137387,44115,93272,0.321100,0.678900
381,Yorkshire and The Humber,Wakefield,246096,71.17,175042,58877,116165,0.336359,0.663641